# # GitHub Actions - Repository secrets
# # HOST
# # PORT
# # USERNAME
# # FOLDER
# # PRIVATE_KEY
# # Ubuntu: Add "CASignatureAlgorithms +ssh-rsa" to /etc/ssh/sshd_config
# # Ubuntu: Add id_rsa.pub to authorized_keys

# name: Release to xfoma.com

# on:
#   push:
#     branches: [main]

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Remote ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             # 1. Update code from github
#             cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/ && /usr/bin/git pull

#             # 2. UV Sync
#             cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && uv sync --no-dev --locked

#             # 4. Copy static files to STATIC_ROOT
#             source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && uv run manage.py collectstatic --noinput

#             # 5. Clean static cache and compress CSS & JS
#             sudo rm -rf /usr/share/nginx/html/static/CACHE
#             source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && uv run manage.py compress --force

#             # 6. Update all static files' user & group permission for STATIC_ROOT
#             sudo chown ${{ secrets.USERNAME }}:www-data -R /usr/share/nginx/html/static/

#             # 7. SEO - Ping Google after update with sitemap
#             # source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && python ./manage.py ping_google

#             # 8. Update Database
#             source /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }}/.venv/bin/activate && cd /home/${{ secrets.USERNAME }}/${{ secrets.FOLDER }} && uv run manage.py migrate

#             # 9. Restart Django and Nginx
#             sudo systemctl restart daphne
#             # sudo systemctl restart djangoq
